version: '3'
services:
    proposta:
        image: mysql:latest
        container_name: proposta
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=my-user
            - MYSQL_PASSWORD=123
            - MYSQL_DATABASE=proposta